upstream connectu_app {
    server app:8001;
}

server {
    listen 80;
    client_max_body_size 10M;

    # Раздача статики
    location /static/ {
        alias /app/staticfiles/;
    }

    # Раздача медиа
    location /media/ {
        alias /app/mediafiles/;
    }

    # Все запросы к /ws/ (наши чаты) идут сюда
    location /ws/ {
        # Указываем на наш правильный upstream
        proxy_pass http://connectu_app;

        # Обязательные заголовки для WebSocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }

    # Все остальные запросы (обычный HTTP) идут сюда
    location / {
        proxy_pass http://connectu_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }
}