# Generated by Django 5.2.8 on 2025-11-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_u_app', '0002_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
