# Generated by Django 5.2.8 on 2025-12-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_u_app', '0002_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='searchable',
            field=models.BooleanField(default=True, verbose_name='Разрешить находить мой профиль в поиске'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_age',
            field=models.BooleanField(default=True, verbose_name='Показывать возраст в профиле'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_city',
            field=models.BooleanField(default=True, verbose_name='Показывать город в профиле'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('searching', 'В поиске'), ('in_relationship', 'В отношениях'), ('not_specified', 'Не указано')], default='not_specified', max_length=20, verbose_name='Статус отношений'),
        ),
    ]
