# Generated by Django 5.2.8 on 2025-11-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_u_app', '0004_dislike_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['name'], 'verbose_name': 'Интерес', 'verbose_name_plural': 'Интересы'},
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название интереса'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='connect_u_app.interest', verbose_name='Интересы'),
        ),
    ]
