# Generated by Django 5.2.8 on 2025-11-30 16:57

import connect_u_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_u_app', '0006_alter_match_options_alter_match_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=connect_u_app.models.user_photos_path),
        ),
    ]
